# =====================================================
# IBM HR Analytics — Employee Attrition
# Final Project | Exploratory Data Analysis (EDA)
# =====================================================
# Group 13 | ESADE MIBA 2026
# Data Analytics with R | Prof. Ruben Coca
# Members: Brice Da Costa, Baran Erdogan, Mats Hoffmann, María Mora, Hiroaki Nakano
#
# Goal:
# Understand the business and employee profile behind attrition
# before building a machine learning model.
#
# Analyst perspective:
# This EDA goes beyond generic descriptive statistics. Every section
# is designed to generate hypotheses about *why* employees leave,
# uncover data quality issues, and prepare the dataset for ML.
#
# Dataset: IBM HR Analytics Employee Attrition & Performance
# Source:   Kaggle (synthetic dataset created by IBM data scientists)
# Rows:    1,470  |  Columns: 35
# =====================================================


# =====================================================
# 1. Libraries
# =====================================================

library(tidyverse)   # dplyr, ggplot2, tidyr, readr, purrr, stringr
library(corrplot)    # Correlation matrix visualization
library(scales)      # Axis label formatting (percent, comma)

# tidyverse is loaded as a meta-package rather than individual libraries
# (readxl, dplyr, ggplot2, etc.) to keep the setup concise and consistent
# with the course conventions.


# =====================================================
# 2. Load Data
# =====================================================

df <- read.csv("./DATA/WA_Fn-UseC_-HR-Employee-Attrition.csv")

str(df)
dim(df)    # Expected: 1,470 rows x 35 columns
head(df)

# The dataset contains 1,470 employee records across 35 variables, covering
# demographic characteristics, job-related attributes, satisfaction scores,
# and a binary attrition flag. str() confirms a mix of character and integer
# columns; head() validates that the import parsed correctly with no
# structural anomalies.


# =====================================================
# 3. Data Quality Review
# =====================================================

# ----- 3.1 Missing values -----

colSums(is.na(df))
cat("\nTotal missing values:", sum(is.na(df)), "\n")

# All 35 variables return zero missing values. This is expected: the dataset
# is synthetically generated by IBM data scientists, so missingness was not
# introduced during collection. In a real-world HR context, missing values
# would be common (for example, employees who skip satisfaction surveys)
# and would themselves carry predictive signal. The absence of missing data
# here means no imputation step is required, but the finding should be
# interpreted as a property of the synthetic generation process rather than
# of genuine HR data.


# ----- 3.2 Duplicate check -----

n_dupes <- sum(duplicated(df))
cat("Duplicate rows:", n_dupes, "\n")

cat("Unique EmployeeNumbers:", length(unique(df$EmployeeNumber)),
    "out of", nrow(df), "rows\n")

# Zero duplicate rows are found. The EmployeeNumber column returns 1,470
# unique values, confirming that each row represents a distinct individual.
# Duplicates would artificially inflate the frequency of certain profiles
# and bias model training; their absence means no deduplication step is needed.


# ----- 3.3 Variable types -----

cat_vars <- sapply(df, is.character)
num_vars <- sapply(df, is.numeric)

cat("\nCategorical variables:\n")
names(df[, cat_vars])

cat("\nNumeric variables:\n")
names(df[, num_vars])

# The dataset contains 9 character variables and 26 integer variables.
# However, several integer columns represent ordered Likert scales rather
# than continuous quantities:
#   - Education (1 = Below College ... 5 = Doctor)
#   - EnvironmentSatisfaction, JobSatisfaction, RelationshipSatisfaction (1–4)
#   - WorkLifeBalance (1 = Bad ... 4 = Best)
#   - JobInvolvement (1–4), PerformanceRating (1–4), StockOptionLevel (0–3)
#   - JobLevel (1–5, hierarchical)
# These are treated as numeric for correlation analysis but are interpreted
# with care: a one-unit increase does not represent the same magnitude at
# every point on the scale. For the ML recipe, ordinal variables will be
# kept numeric unless step_dummy() is applied.


# ----- 3.4 Frequency tables for categorical variables -----

lapply(df[, cat_vars], table)
lapply(df[, cat_vars], function(x) round(prop.table(table(x)), 3))

# Frequency and proportion tables reveal the workforce composition across
# all categorical predictors. Key observations: the dataset skews heavily
# toward male employees (~60%), Research & Development is the largest
# department (~65%), and the majority of employees are non-overtime workers
# (~71.7%). These compositions will be important context when interpreting
# attrition rates by subgroup, as a high attrition rate in a small group
# (e.g., HR department) may reflect fewer than 20 employees in absolute terms.


# ----- 3.5 Summary statistics for numeric variables -----

df %>%
  select(where(is.numeric)) %>%
  summary()

# Summary statistics highlight several key distributional features.
# MonthlyIncome is heavily right-skewed (median ~$4,919; mean ~$6,503),
# reflecting the pyramid structure of most organisations, many junior
# employees and few senior earners. Age ranges from 18 to 60 with a median
# of 36. TotalWorkingYears and YearsAtCompany are both right-skewed,
# indicating that the workforce is predominantly early-to-mid career.
# These skews are relevant for model pre-processing: tree-based algorithms
# handle them natively, but linear models would benefit from log-transformation
# of income and tenure variables.


# ----- 3.6 Constant and near-constant variables -----

unique_counts <- sapply(df, function(x) length(unique(x)))
sort(unique_counts)

constant_vars <- names(df)[unique_counts == 1]
cat("\nConstant variables (will be removed):\n")
print(constant_vars)

# Three variables are identified as constants: EmployeeCount (always 1),
# Over18 (always "Y"), and StandardHours (always 80). Variables with zero
# variance provide no discriminative information for a classification model
# and will be excluded in the ML preparation step. EmployeeNumber (1,470
# unique values) is also flagged for removal: it is a unique row identifier
# with no predictive meaning; including it would cause data leakage.


# ----- 3.7 Synthetic data acknowledgment -----

# This is an IBM-created synthetic dataset, not real employee data. Three
# implications bear directly on the analysis:
# (a) The absence of missing values and duplicates is by design, not a
#     reflection of data quality practices.
# (b) Several rate variables (DailyRate, HourlyRate, MonthlyRate) appear to
#     be independently drawn random numbers rather than consistent
#     compensation components, as verified in Section 7.2.
# (c) Statistical findings should be interpreted as methodological exercises.
#     The relationships found here may not generalise to real HR datasets.


# =====================================================
# 4. Target Variable Analysis: Attrition
# =====================================================

table(df$Attrition)
prop.table(table(df$Attrition))

# The target variable is binary: 237 employees left ("Yes", 16.1%) versus
# 1,233 who stayed ("No", 83.9%). This constitutes moderate class imbalance.
# It is not extreme; fraud detection datasets, for example, often present
# <1% positive class, but it is sufficient to bias a naive classifier toward
# always predicting "No" and achieving ~84% accuracy without learning anything
# useful. In the ML phase, this imbalance will be addressed through
# oversampling (SMOTE via the themis package) and threshold optimisation
# using the J-index rather than defaulting to the 0.5 probability cutoff.

ggplot(df, aes(x = Attrition, fill = Attrition)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.1))) +
  scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(
    title    = "Employee Attrition Distribution",
    subtitle = paste0("Imbalanced: ", round(mean(df$Attrition == "Yes") * 100, 1),
                      "% attrition rate (n = ", nrow(df), ")"),
    x = "Attrition", y = "Number of Employees"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

# The bar chart provides immediate visual context for the class imbalance.
# A simple bar chart is chosen over a pie chart because it enables direct
# length-based comparison and accommodates absolute counts as annotations.
# The colour scheme (red = attrition, blue = retention) is used consistently
# throughout the EDA to facilitate pattern recognition across plots.


# =====================================================
# 5. Distribution of Numeric Variables
# =====================================================

num_cols <- names(df)[num_vars]

# ----- 5.1 Faceted histograms (all numeric variables) -----

df %>%
  select(where(is.numeric), -EmployeeNumber, -EmployeeCount, -StandardHours) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white", alpha = 0.8) +
  facet_wrap(~ variable, scales = "free", ncol = 5) +
  labs(title = "Distributions of All Numeric Variables") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold", size = 7),
        axis.text  = element_text(size = 6))

# A faceted histogram with free axis scales is used rather than individual
# plots to give a compact side-by-side overview of all 23 numeric variables
# simultaneously. Several patterns emerge: MonthlyIncome, TotalWorkingYears,
# and YearsAtCompany are right-skewed, consistent with workforce seniority
# pyramids. Age approximates a roughly normal distribution centred near 36.
# The Likert-scale variables (JobSatisfaction, WorkLifeBalance, etc.) show
# discrete uniform-to-slightly-left-skewed distributions across their 1–4
# range. The three rate variables (DailyRate, HourlyRate, MonthlyRate)
# display near-uniform distributions, an anomaly explored in Section 7.2.


# ----- 5.2 Faceted histograms by Attrition status -----

df %>%
  select(where(is.numeric), Attrition,
         -EmployeeNumber, -EmployeeCount, -StandardHours) %>%
  pivot_longer(-Attrition, names_to = "variable", values_to = "value") %>%
  ggplot(aes(x = value, fill = Attrition)) +
  geom_histogram(bins = 30, alpha = 0.6, position = "identity", color = "white") +
  facet_wrap(~ variable, scales = "free", ncol = 5) +
  scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(title = "Numeric Distributions by Attrition Status") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold", size = 7),
        axis.text  = element_text(size = 6),
        legend.position = "bottom")

# Overlaying both classes in the same histogram (position = "identity" with
# alpha transparency) reveals which variables show distributional separation
# between leavers and stayers. Variables where the two distributions clearly
# diverge: MonthlyIncome, Age, TotalWorkingYears, and JobLevel, which are strong
# candidate predictors. Variables where the distributions largely overlap
# (DailyRate, HourlyRate, MonthlyRate) offer minimal discriminative power.
# This visual screen motivates the more rigorous point-biserial correlation
# analysis in Section 7.3.


# =====================================================
# 6. Outlier Review
# =====================================================

# Outliers in HR data are not necessarily data errors. A very high income
# reflects senior management; a long tenure reflects loyalty. The goal here
# is to understand the workforce structure, not to remove legitimate data points.

# ----- 6.1 Boxplots for key numeric variables -----

num_vars_box <- df %>%
  select(where(is.numeric)) %>%
  select(-EmployeeNumber, -EmployeeCount, -StandardHours)

for (col in names(num_vars_box)) {
  print(
    ggplot(df, aes(x = "", y = .data[[col]])) +
      geom_boxplot(fill = "orange", alpha = 0.7, outlier.color = "red") +
      ggtitle(paste("Boxplot of", col)) +
      theme_minimal()
  )
}

# Boxplots are used because they display the IQR, median, and outlier
# positions simultaneously. Individual plots per variable are generated
# inside a for-loop rather than a facet to allow the y-axis to scale
# appropriately for each variable's range. Flagged outliers (red points)
# are visible primarily in MonthlyIncome, NumCompaniesWorked, and the
# tenure-related variables, consistent with the right-skewed distributions
# observed in Section 5.


# ----- 6.2 IQR outlier summary -----

outlier_summary <- lapply(names(num_vars_box), function(col) {
  x  <- df[[col]]
  q1 <- quantile(x, 0.25, na.rm = TRUE)
  q3 <- quantile(x, 0.75, na.rm = TRUE)
  iqr <- q3 - q1
  lower <- q1 - 1.5 * iqr
  upper <- q3 + 1.5 * iqr
  outliers <- sum(x < lower | x > upper, na.rm = TRUE)
  data.frame(
    variable     = col,
    outliers     = outliers,
    pct_outliers = round(outliers / nrow(df) * 100, 1)
  )
}) %>% bind_rows()

outlier_summary %>% arrange(desc(outliers))

# The IQR rule (flag values below Q1 − 1.5×IQR or above Q3 + 1.5×IQR) is
# applied programmatically across all numeric variables. The highest outlier
# counts belong to TrainingTimesLastYear (238 flagged, 16.2%) and
# PerformanceRating (226, 15.4%), both reflecting discrete scales where a few
# values dominate. MonthlyIncome ranks third (114 flagged, 7.8%), reflecting
# the long right tail of senior-level compensation. YearsSinceLastPromotion
# (7.3%) and YearsAtCompany (7.1%) also flag several long-tenure employees.
# None of these observations are removed: (a) they represent real and
# plausible employee profiles; (b) the tree-based models used in the ML phase
# (Random Forest, XGBoost) are robust to outliers by construction; splits
# are based on rank-order thresholds, not distances from the mean; (c)
# removing senior profiles would introduce systematic bias against
# high-earners in the attrition model.


# =====================================================
# 7. Correlation Analysis
# =====================================================

# ----- 7.1 Pearson correlation matrix -----

# A Pearson correlation matrix is computed across all numeric predictors to
# identify redundancy and potential multicollinearity. Corrplot with
# coefficient annotations is chosen over a simple heatmap because it renders
# both the magnitude (colour intensity) and direction (colour hue) of
# correlations while displaying exact values for precision.

num_df_corr <- df %>%
  select(where(is.numeric)) %>%
  select(-EmployeeNumber, -EmployeeCount, -StandardHours)

cor_matrix <- cor(num_df_corr)
corrplot(cor_matrix, method = "color", type = "upper", tl.cex = 0.6,
         addCoef.col = "black", number.cex = 0.5)

cor_pairs <- as.data.frame(as.table(cor_matrix)) %>%
  rename(var1 = Var1, var2 = Var2, correlation = Freq) %>%
  mutate(var1 = as.character(var1), var2 = as.character(var2)) %>%
  filter(var1 != var2) %>%
  mutate(pair = paste(pmin(var1, var2), pmax(var1, var2), sep = " — ")) %>%
  distinct(pair, .keep_all = TRUE) %>%
  filter(abs(correlation) >= 0.70) %>%
  arrange(desc(abs(correlation)))

cat("\nStrongly correlated pairs (|r| >= 0.70):\n")
print(cor_pairs)

# Seven strongly correlated variable pairs emerge (|r| >= 0.70):
#   - MonthlyIncome ~ JobLevel (r = 0.95): the strongest pair; job level
#     is essentially a seniority rank, so higher levels command substantially
#     higher pay by design.
#   - TotalWorkingYears ~ JobLevel (r = 0.78): more experienced employees
#     tend to hold higher-level positions.
#   - PerformanceRating ~ PercentSalaryHike (r = 0.77): higher performers
#     receive larger salary increases, consistent with a merit-based system.
#   - TotalWorkingYears ~ MonthlyIncome (r = 0.77): more experience
#     commands higher pay independently of job level.
#   - YearsAtCompany ~ YearsWithCurrManager (r = 0.77) and
#     YearsAtCompany ~ YearsInCurrentRole (r = 0.76): logically nested,
#     as tenure with a manager or in a role cannot exceed total company tenure.
#   - YearsWithCurrManager ~ YearsInCurrentRole (r = 0.71): employees who
#     have been in their role longer tend to have the same manager longer.
# These correlations are substantively meaningful rather than problematic data errors.
# In the ML phase, multicollinearity is handled mainly by the tree-based algorithms,
# which are less sensitive to correlated predictors. We kept the preprocessing recipe
# simple and used step_nzv(), while retaining correlated variables so the models could
# determine which ones were most informative.

# ----- 7.2 Noise variable verification -----

# DailyRate, HourlyRate, and MonthlyRate are inspected for their relationship
# to MonthlyIncome. In a real compensation system, DailyRate ≈ MonthlyIncome
# / ~22 working days, so the three variables should therefore be tightly
# correlated. Near-zero correlation would indicate they were generated
# independently and carry no compensation signal.

df_temp <- df %>%
  mutate(Attrition_bin = ifelse(Attrition == "Yes", 1, 0))

noise_check <- tibble(
  Variable = c("DailyRate", "HourlyRate", "MonthlyRate"),
  cor_with_MonthlyIncome = c(
    cor(df$DailyRate,   df$MonthlyIncome),
    cor(df$HourlyRate,  df$MonthlyIncome),
    cor(df$MonthlyRate, df$MonthlyIncome)
  ),
  cor_with_Attrition = c(
    cor(df_temp$DailyRate,   df_temp$Attrition_bin),
    cor(df_temp$HourlyRate,  df_temp$Attrition_bin),
    cor(df_temp$MonthlyRate, df_temp$Attrition_bin)
  )
)

cat("\nNoise variable check:\n")
print(noise_check)

# All three rate variables show near-zero correlation with both MonthlyIncome
# (|r| < 0.04) and Attrition (|r| < 0.06). This confirms that DailyRate,
# HourlyRate, and MonthlyRate were drawn as independent random numbers during
# synthetic data generation and do not represent coherent compensation
# components. They are retained in df_ml.csv for app.R compatibility but
# are noted as noise variables. Their presence will marginally inflate model
# complexity without contributing predictive signal.


# ----- 7.3 Point-biserial correlations with Attrition -----

# Point-biserial correlation measures the linear association between a
# continuous predictor and a binary outcome variable. It is numerically
# equivalent to Pearson r when one variable is dichotomous (coded 0/1).
# This provides a ranked list of numeric predictors by their individual
# association strength with attrition, which guides variable selection
# discussion and helps prioritise which distributions to examine in depth.

pb_correlations <- df_temp %>%
  select(where(is.numeric), -EmployeeNumber, -EmployeeCount,
         -StandardHours, -Attrition_bin) %>%
  summarise(across(everything(), ~ cor(.x, df_temp$Attrition_bin))) %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "r_pb") %>%
  mutate(abs_r = abs(r_pb)) %>%
  arrange(desc(abs_r))

cat("\nPoint-biserial correlations with Attrition:\n")
print(pb_correlations, n = 25)

ggplot(pb_correlations, aes(x = reorder(Variable, r_pb), y = r_pb)) +
  geom_col(aes(fill = r_pb > 0), show.legend = FALSE) +
  scale_fill_manual(values = c("TRUE" = "#E74C3C", "FALSE" = "#3498DB")) +
  coord_flip() +
  labs(
    title = "Point-Biserial Correlation with Attrition",
    subtitle = "Positive = higher value associated with more attrition",
    x = NULL, y = "Correlation (r)"
  ) +
  theme_minimal()

# The strongest negative correlations (higher value → lower attrition) belong
# to TotalWorkingYears, JobLevel, MonthlyIncome, Age, YearsInCurrentRole,
# StockOptionLevel, and YearsWithCurrManager. These jointly describe the
# "settled senior employee" profile: well-compensated, experienced,
# established in their role and managerial relationship, who rarely leaves.
# OverTime is the strongest categorical predictor overall, but because it is
# not numeric it is excluded from this point-biserial analysis and evaluated
# separately via chi-square in Section 8. Near-zero correlations for
# DailyRate, HourlyRate, MonthlyRate, and PerformanceRating confirm the
# noise finding above. This ranking directly informs which numeric variables
# receive detailed violin plot analysis in Section 10.


# =====================================================
# 8. Statistical Tests: Categorical Variables vs Attrition
# =====================================================

# Chi-square tests of independence are used to assess whether the association
# between each categorical predictor and Attrition is statistically
# significant. The null hypothesis (H0) for each test is that the variable
# is independent of attrition status. Cramér's V is computed as an effect
# size measure, ranging from 0 (no association) to 1 (perfect association),
# and allows comparison across variables with different numbers of categories.
# Monte Carlo simulation (simulate.p.value = TRUE, B = 2000) is used rather
# than the asymptotic chi-square approximation because some cell counts are
# small, which violates the standard approximation's assumptions.
# set.seed(123) is set before the block to ensure the simulation results
# are fully reproducible across runs.

# Over18 is excluded from the chi-square analysis: it is a constant variable
# (all employees are "Y") identified in Section 3.6, so the test would produce
# an undefined Cramér's V (division by zero). EDA-engineered columns
# (AgeGroup, IncomeGroup, AvgSatisfaction) are also excluded as they are
# derived variables, not original predictors. Only the seven original
# categorical predictors are tested.
set.seed(123)
cat_var_names <- c("BusinessTravel", "Department", "EducationField",
                   "Gender", "JobRole", "MaritalStatus", "OverTime")

chi_sq_results <- map_dfr(cat_var_names, function(var) {
  tbl <- table(df[[var]], df$Attrition)
  test <- chisq.test(tbl, simulate.p.value = TRUE, B = 2000)
  n <- sum(tbl)
  k <- min(nrow(tbl), ncol(tbl))
  cramers_v <- sqrt(test$statistic / (n * (k - 1)))
  tibble(
    Variable  = var,
    chi_sq    = round(test$statistic, 2),
    p_value   = signif(test$p.value, 3),
    cramers_v = round(cramers_v, 3),
    significant = ifelse(test$p.value < 0.05, "Yes", "No")
  )
})

cat("\nChi-square tests: Categorical variables vs Attrition\n")
print(chi_sq_results %>% arrange(desc(cramers_v)))

# Results ranked by Cramér's V:
#   - OverTime: p < 0.001, V = 0.246: the strongest categorical predictor.
#     We reject H0: overtime status is significantly associated with attrition.
#   - JobRole: p < 0.001, V = 0.242: nearly as strong as OverTime; job role
#     differentiates attrition rates substantially across the nine categories.
#   - MaritalStatus: p < 0.001, V = 0.177: significant; single employees
#     show markedly higher attrition than married or divorced peers.
#   - BusinessTravel: p < 0.001, V = 0.128: significant; frequent travellers
#     have meaningfully higher attrition than non-travellers.
#   - EducationField: p = 0.009, V = 0.104: significant but modest effect.
#   - Department: p = 0.0045, V = 0.086: significant; weaker than job role,
#     which captures the same variance more granularly.
#   - Gender: p = 0.258 > 0.05: we fail to reject H0; gender shows no
#     statistically significant association with attrition at the 5% level.
# All significant categorical predictors are included in the ML feature set.


# =====================================================
# 9. Attrition-Focused EDA: Categorical Variables
# =====================================================

# For each categorical predictor, stacked proportional bar charts are used
# rather than raw count bars. Because pct is computed explicitly before
# plotting, geom_col() with position_stack() is used rather than
# position = "fill", which avoids redundant rescaling and gives direct
# control over label placement. A helper function is defined to avoid
# repetitive code across the seven categorical variables examined.

plot_attrition_cat <- function(data, var, title) {
  data %>%
    count(.data[[var]], Attrition) %>%
    group_by(.data[[var]]) %>%
    mutate(pct = n / sum(n)) %>%
    ggplot(aes(x = .data[[var]], y = pct, fill = Attrition)) +
    geom_col() +
    geom_text(aes(label = scales::percent(pct, accuracy = 0.1)),
              position = position_stack(vjust = 0.5), size = 3, color = "white") +
    scale_y_continuous(labels = percent) +
    scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
    labs(title = title, x = var, y = "Proportion") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}


# ----- 9.1 Attrition vs OverTime -----

table(df$Attrition, df$OverTime)
prop.table(table(df$Attrition, df$OverTime), margin = 2)

plot_attrition_cat(df, "OverTime", "Attrition by OverTime")

# Employees who work overtime show an attrition rate of approximately 30.5%,
# compared to 10.4% for those who do not. This ~3x multiplier makes OverTime
# the single strongest individual predictor in the dataset, consistent with
# its leading Cramér's V in Section 8. The mechanism is intuitive: sustained
# overtime is a primary driver of burnout, which erodes both job satisfaction
# and organisational commitment. From a retention standpoint, the 70% of
# overtime workers who do stay represent a heterogeneous group; some are
# compensated or motivated sufficiently to tolerate the workload. The ML
# model will help identify which overtime workers are genuinely at risk by
# combining this signal with satisfaction scores, tenure, and compensation.


# ----- 9.2 Attrition vs JobRole -----

table(df$Attrition, df$JobRole)
prop.table(table(df$Attrition, df$JobRole), margin = 2)

plot_attrition_cat(df, "JobRole", "Attrition by Job Role")

# Sales Representatives show the highest attrition rate (~39.8%), followed
# by Laboratory Technicians (~23.9%) and Human Resources staff (~23.1%).
# Research Directors have the lowest rate (~2.5%), followed by Manufacturing
# Directors (~6.9%). The Sales Representative figure reflects well-documented
# patterns in sales-intensive industries: high performance targets, variable
# compensation, and strong external demand for sales talent create
# structurally elevated turnover. The model should be interpreted in context
# of role; a 20% attrition probability is very different in meaning for a
# Sales Rep versus a Research Director.


# ----- 9.3 Attrition vs Department -----

table(df$Attrition, df$Department)
prop.table(table(df$Attrition, df$Department), margin = 2)

plot_attrition_cat(df, "Department", "Attrition by Department")

# Sales has the highest departmental attrition rate (~20.6%), followed by
# Human Resources (~19.0%) and Research & Development (~13.8%). Department
# is partially a proxy for job role composition: the Sales department
# contains the high-attrition Sales Representatives, while R&D contains
# the low-attrition Research Directors. Department will be included as a
# predictor, though JobRole likely captures its signal more granularly.


# ----- 9.4 Attrition vs MaritalStatus -----

table(df$Attrition, df$MaritalStatus)
prop.table(table(df$Attrition, df$MaritalStatus), margin = 2)

plot_attrition_cat(df, "MaritalStatus", "Attrition by Marital Status")

# Single employees have an attrition rate of approximately 25.5%, compared
# to 12.5% for married and 10.1% for divorced employees. The pattern likely
# reflects an interaction with age, as single employees in this dataset tend
# to be younger, earlier in their careers, and therefore more mobile.
# Marital status also proxies for financial commitments: employees with
# dependents, mortgages, or dual-income households may face higher switching
# costs. This interaction will not be explicitly modelled but is a
# substantive reason to include both MaritalStatus and Age as predictors.


# ----- 9.5 Attrition vs BusinessTravel -----

table(df$Attrition, df$BusinessTravel)
prop.table(table(df$Attrition, df$BusinessTravel), margin = 2)

plot_attrition_cat(df, "BusinessTravel", "Attrition by Business Travel")

# Employees who travel frequently for business show an attrition rate of
# approximately 24.9%, versus 15.0% for those who travel rarely and 8.0%
# for non-travellers. Frequent travel is associated with family disruption
# and reduced work-life balance, consistent with an additive burnout
# mechanism similar to OverTime. The monotonic increase across travel
# frequency categories validates using the variable as an ordinal or
# dummy-encoded predictor in the ML recipe.


# ----- 9.6 Attrition vs Gender -----

table(df$Attrition, df$Gender)
prop.table(table(df$Attrition, df$Gender), margin = 2)

plot_attrition_cat(df, "Gender", "Attrition by Gender")

# Male and female employees show attrition rates of approximately 17.0% and
# 14.8% respectively, a difference of ~2 percentage points. This is
# consistent with the chi-square result in Section 8, where gender did not
# reach statistical significance (p = 0.258 > 0.05). The substantive conclusion is
# that gender is not a meaningful driver of attrition in this dataset.
# It will be included in the ML feature set to allow the model to capture
# potential interaction effects, but it is not expected to rank highly in
# variable importance.


# ----- 9.7 Attrition vs EducationField -----

table(df$Attrition, df$EducationField)
prop.table(table(df$Attrition, df$EducationField), margin = 2)

plot_attrition_cat(df, "EducationField", "Attrition by Education Field")

# Human Resources as an education field shows the highest attrition rate
# (~25.9%), followed by Technical Degree (~24.2%) and Marketing (~22.0%).
# Life Sciences (~14.7%) and Medical (~13.6%) fields show rates below the
# dataset baseline of 16.1%. Other fields show ~13.4%. These differences
# partly reflect which job roles attract each educational background:
# HR-educated employees are more likely to be in the HR role (high attrition),
# while Medical-educated employees are more likely to be in R&D roles
# (lower attrition). Sample sizes vary substantially across fields, which
# limits the reliability of point estimates for smaller groups.


# =====================================================
# 10. Attrition-Focused EDA: Numeric Variables
# =====================================================

# Violin plots combined with embedded boxplots are used for numeric variables
# rather than simple boxplots or histograms. This combination shows the full
# distribution shape (kernel density estimate, from the violin) alongside
# median, IQR, and whiskers (from the boxplot). This is more informative than
# a boxplot alone when distributions are multimodal or asymmetric, as is
# common in HR tenure and compensation data.

# ----- 10.1 Key numeric variables vs Attrition -----

key_numeric <- c("Age", "MonthlyIncome", "TotalWorkingYears",
                 "YearsAtCompany", "DistanceFromHome",
                 "YearsInCurrentRole", "YearsSinceLastPromotion",
                 "NumCompaniesWorked")

for (col in key_numeric) {
  print(
    ggplot(df, aes(x = Attrition, y = .data[[col]], fill = Attrition)) +
      geom_violin(alpha = 0.6, trim = FALSE) +
      geom_boxplot(width = 0.15, fill = "white", alpha = 0.8) +
      scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
      labs(title = paste(col, "by Attrition")) +
      theme_minimal() +
      theme(legend.position = "none")
  )
}

# Key patterns across the violin plots:
#   - MonthlyIncome: leavers are concentrated in the lower-income range;
#     stayers show a much longer right tail representing senior earners.
#     The difference in medians is visually large and consistent with the
#     strong negative point-biserial correlation found in Section 7.3.
#   - Age: leavers peak around 28–32, stayers are more evenly distributed
#     across the 30–50 range. Early-career employees are the highest-risk
#     age cohort.
#   - TotalWorkingYears: leavers cluster at 0–8 years of experience.
#     The distribution for stayers extends much further, confirming that
#     experience and tenure are protective against attrition.
#   - YearsAtCompany: leavers concentrate at 0–5 years; the first years
#     at a company appear to be the highest-risk window.
#   - DistanceFromHome: a modest shift is visible; leavers tend to live
#     slightly farther from the office, consistent with commute burden
#     as a secondary attrition driver.
#   - YearsSinceLastPromotion: distributions overlap substantially,
#     suggesting promotion recency alone is not a strong linear predictor
#     as it may interact with tenure and satisfaction.


# ----- 10.2 Satisfaction variables (Likert scales 1–4) -----

# Satisfaction variables are ordinal (1–4 scale) rather than continuous.
# Grouped dodged bar charts are used instead of violin plots because they
# correctly represent the discrete, bounded nature of Likert data: treating
# ordinal scores as continuous would obscure the step-function character
# of the underlying scale.

satisfaction_vars <- c("JobSatisfaction", "EnvironmentSatisfaction",
                       "RelationshipSatisfaction", "WorkLifeBalance",
                       "JobInvolvement")

for (col in satisfaction_vars) {
  print(
    df %>%
      count(Attrition, val = factor(.data[[col]])) %>%
      group_by(Attrition) %>%
      mutate(pct = n / sum(n)) %>%
      ggplot(aes(x = val, y = pct, fill = Attrition)) +
      geom_col(position = "dodge") +
      scale_y_continuous(labels = percent) +
      scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
      labs(title = paste(col, "by Attrition"),
           x = paste(col, "(1 = Low, 4 = High)"), y = "Proportion") +
      theme_minimal()
  )
}

# Across all five satisfaction variables, employees who left show a higher
# proportion reporting the lowest score (level 1) relative to stayers.
# The effect is most pronounced for JobInvolvement, where leavers show a
# notably higher mass at level 1. The distributions are broadly similar at
# higher levels, indicating that dissatisfaction is an asymmetric risk factor:
# low satisfaction is associated with elevated attrition, but moderate-to-high
# satisfaction does not guarantee retention. Employees at satisfaction level 2
# are of particular strategic interest; they are dissatisfied but still
# present, and represent the group most likely to respond positively to a
# targeted retention intervention.


# =====================================================
# 11. Grouped Business Summaries by Attrition
# =====================================================

# A grouped summary table condenses the EDA into a format that is
# interpretable by non-technical stakeholders. Means by attrition status
# describe the "typical leaver" and "typical stayer" profile.

attrition_numeric_summary <- df %>%
  group_by(Attrition) %>%
  summarise(
    n                          = n(),
    avg_age                    = round(mean(Age), 1),
    avg_monthly_income         = round(mean(MonthlyIncome), 0),
    avg_total_working_years    = round(mean(TotalWorkingYears), 1),
    avg_years_at_company       = round(mean(YearsAtCompany), 1),
    avg_distance_from_home     = round(mean(DistanceFromHome), 1),
    avg_job_satisfaction       = round(mean(JobSatisfaction), 2),
    avg_env_satisfaction       = round(mean(EnvironmentSatisfaction), 2),
    avg_work_life_balance      = round(mean(WorkLifeBalance), 2),
    avg_num_companies_worked   = round(mean(NumCompaniesWorked), 1),
    avg_years_since_promotion  = round(mean(YearsSinceLastPromotion), 1),
    pct_overtime               = round(mean(OverTime == "Yes") * 100, 1)
  )

print(attrition_numeric_summary)

# The summary table confirms and quantifies the patterns found in individual
# variable analyses. Relative to stayers, leavers are on average: 4.0 years
# younger (33.6 vs 37.6), earn ~$2,046/month less (4,787 vs 6,833), have
# 3.7 fewer total working years (8.2 vs 11.9), and a much higher percentage
# work overtime. Satisfaction score differences are present but modest (~0.2
# points on a 1–4 scale). The overtime gap is the largest proportional
# difference across all variables, reinforcing its identification as the
# primary actionable predictor. These averages characterise the typical leaver
# but mask important variation; the ML model's probability output will
# capture the combination of risk factors for individual employees more
# precisely than any single average profile.


# =====================================================
# 12. Attrition Rate by Category (Ranking View)
# =====================================================

# Ranked horizontal bar charts of attrition rates are used to communicate
# the relative risk across categories in a format readily interpretable by
# HR stakeholders. Proportional rates rather than raw counts are shown because
# they are directly comparable across groups of different sizes. A helper
# function avoids code repetition across the five categorical variables.

plot_attrition_rate <- function(data, group_var, title) {
  data %>%
    group_by(.data[[group_var]]) %>%
    summarise(
      employees      = n(),
      attrition_rate = mean(Attrition == "Yes"),
      .groups = "drop"
    ) %>%
    arrange(desc(attrition_rate)) %>%
    ggplot(aes(x = reorder(.data[[group_var]], attrition_rate),
               y = attrition_rate)) +
    geom_col(fill = "steelblue") +
    geom_text(aes(label = paste0(round(attrition_rate * 100, 1), "%")),
              hjust = -0.1, size = 3) +
    scale_y_continuous(labels = percent,
                       expand = expansion(mult = c(0, 0.15))) +
    coord_flip() +
    labs(title = title, x = NULL, y = "Attrition Rate") +
    theme_minimal()
}

plot_attrition_rate(df, "JobRole",        "Attrition Rate by Job Role")
plot_attrition_rate(df, "Department",     "Attrition Rate by Department")
plot_attrition_rate(df, "BusinessTravel", "Attrition Rate by Business Travel")
plot_attrition_rate(df, "EducationField", "Attrition Rate by Education Field")
plot_attrition_rate(df, "MaritalStatus",  "Attrition Rate by Marital Status")

# These charts complement Section 9 by providing a clean ranked view across
# all categories of each variable simultaneously. A key nuance is that the
# highest-rate group is not always where intervention resources are most
# efficiently deployed: a 40% attrition rate in a 10-person group represents
# 4 departures; a 15% rate in a 200-person group represents 30 departures and
# a larger total organisational impact. Additionally, groups close to the
# overall average attrition rate (~16%) are more likely to contain employees
# who are "on the edge" and responsive to intervention, whereas very
# high-rate groups may include employees with strong external pulls (e.g.,
# Sales Reps with competing offers) where retention is structurally more
# difficult.


# =====================================================
# 13. Age and Income Binning
# =====================================================

# Continuous variables are binned into meaningful business categories to test
# for non-linear patterns in attrition risk. Binning is used here for
# exploratory visualisation only; the original continuous variables are
# retained for the ML recipe to avoid information loss through discretisation.

# ----- 13.1 Age groups -----

df <- df %>%
  mutate(AgeGroup = cut(Age,
                        breaks = c(17, 25, 35, 45, 55, 61),
                        labels = c("18-25", "26-35", "36-45", "46-55", "56-60")))

df %>%
  group_by(AgeGroup) %>%
  summarise(n = n(), attrition_rate = round(mean(Attrition == "Yes") * 100, 1)) %>%
  print()

plot_attrition_rate(df, "AgeGroup", "Attrition Rate by Age Group")

# The youngest cohort (18–25) shows the highest attrition rate (~35.8%),
# which decreases through the 26–35 (~19.1%) and 36–45 (~9.2%) groups.
# The 46–55 group shows a rate of ~11.5%, while the 56–60 group rises
# slightly to ~17.0%, likely reflecting employees approaching retirement
# or voluntary career transitions. The overall pattern confirms a non-linear
# age effect that linear correlation alone would understate: attrition risk
# is highest in the earliest career stage and diminishes substantially
# through mid-career. This non-linearity is naturally captured by tree-based
# models, which can discover threshold-based splits.


# ----- 13.2 Income brackets -----

df <- df %>%
  mutate(IncomeGroup = cut(MonthlyIncome,
                           breaks = c(0, 3000, 6000, 10000, 20000),
                           labels = c("Low (<3K)", "Mid (3-6K)",
                                      "Upper-Mid (6-10K)", "High (10K+)")))

df %>%
  group_by(IncomeGroup) %>%
  summarise(n = n(), attrition_rate = round(mean(Attrition == "Yes") * 100, 1)) %>%
  print()

plot_attrition_rate(df, "IncomeGroup", "Attrition Rate by Income Bracket")

# Low-income employees (< $3,000/month) show an attrition rate of ~28.6%,
# declining to ~12.7% in the mid-income bracket (3K–6K), ~12.0% in the
# upper-mid bracket (6K–10K), and ~8.9% at the highest income level (10K+).
# Compensation appears to operate as a hygiene factor: below a certain
# threshold, inadequate pay directly drives attrition. Above that threshold,
# other factors (overtime load, career progression, and satisfaction) become
# the dominant drivers. This non-linear pattern reinforces the rationale
# for keeping MonthlyIncome as a continuous predictor in the ML model
# rather than as a bucketed variable.


# =====================================================
# 14. Key HR Hypotheses
# =====================================================

# The following analyses target three specific HR hypotheses that emerge
# from the variable-by-variable EDA: (1) overtime is associated with
# reduced work-life balance; (2) income increases monotonically with job
# level, validating the dataset's internal consistency; and (3) short tenure
# and low income are jointly associated with attrition.

# ----- 14.1 Overtime and work-life balance -----

ggplot(df, aes(x = OverTime, y = WorkLifeBalance, fill = OverTime)) +
  geom_violin(alpha = 0.6) +
  geom_boxplot(width = 0.15, fill = "white") +
  labs(title = "Work-Life Balance by OverTime") +
  theme_minimal() +
  theme(legend.position = "none")

# Employees who work overtime show a distribution of work-life balance scores
# that is shifted slightly toward the lower end of the 1–4 scale, relative
# to non-overtime workers. However, the distributions substantially overlap,
# indicating that overtime and work-life balance are related but not
# redundant; some overtime workers report good work-life balance, and some
# non-overtime workers report poor balance. Both variables independently
# contribute attrition signal and both are retained in the ML feature set.


# ----- 14.2 Income by job level -----

ggplot(df, aes(x = factor(JobLevel), y = MonthlyIncome,
               fill = factor(JobLevel))) +
  geom_boxplot() +
  labs(title = "Monthly Income by Job Level",
       x = "Job Level", y = "Monthly Income") +
  theme_minimal() +
  theme(legend.position = "none")

# Monthly income increases monotonically with job level (1 through 5), with
# each level showing a clear upward shift in both median and spread. This
# validates the internal structure of the synthetic dataset: JobLevel
# represents a genuine seniority hierarchy, not an arbitrary categorical
# label. The strong correlation between JobLevel and MonthlyIncome (captured
# in Section 7.1) means these two variables carry overlapping signal;
# the tree-based model will select the more informative one at each split.


# ----- 14.3 Years at company vs income, by attrition -----

ggplot(df, aes(x = YearsAtCompany, y = MonthlyIncome, color = Attrition)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(title = "Years at Company vs Monthly Income",
       x = "Years at Company", y = "Monthly Income") +
  theme_minimal()

# Attrition cases (red points) cluster densely in the lower-left quadrant,
# short tenure and low income, confirming that early-career, lower-paid
# employees represent the highest-risk segment. The upper-right quadrant
# (long tenure, high income) is almost exclusively blue (stayers). This
# scatterplot provides a clear visual justification for why both
# YearsAtCompany and MonthlyIncome should be retained as predictors:
# they jointly define the risk profile better than either alone.


# ----- 14.4 Composite satisfaction score -----

# The four satisfaction variables (JobSatisfaction, EnvironmentSatisfaction,
# RelationshipSatisfaction, WorkLifeBalance) each capture a distinct
# dimension of engagement. An unweighted average is computed here as an
# exploratory tool to test whether a single composite score discriminates
# attrition as well as the individual variables. This composite will be
# created inside the ML recipe using step_mutate() if it proves useful,
# it is not saved to df_ml.csv to avoid redundant features.

df <- df %>%
  mutate(AvgSatisfaction = (JobSatisfaction + EnvironmentSatisfaction +
                              RelationshipSatisfaction + WorkLifeBalance) / 4)

ggplot(df, aes(x = Attrition, y = AvgSatisfaction, fill = Attrition)) +
  geom_violin(alpha = 0.6, trim = FALSE) +
  geom_boxplot(width = 0.15, fill = "white") +
  scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(title = "Average Satisfaction Score by Attrition",
       subtitle = "Mean of JobSat, EnvSat, RelSat, WorkLifeBalance (each 1–4)",
       y = "Average Satisfaction (1–4)") +
  theme_minimal() +
  theme(legend.position = "none")

# Leavers show a marginally lower median composite satisfaction score than
# stayers, but the two distributions overlap substantially. The composite
# score does not reveal strong additional discrimination beyond what the
# individual satisfaction variables already provide. This suggests that
# satisfaction alone may not fully explain attrition in this dataset.
# Other factors such as overtime, promotion stagnation, commute distance,
# compensation, and business travel also appear to contribute meaningfully.
# From a business perspective, this is useful: the overlap implies that
# many at-risk employees are not yet deeply disengaged, so targeted HR
# interventions may still be effective.


# =====================================================
# 15. Data Preparation for Machine Learning
# =====================================================

# Before exporting the ML-ready dataset, the following variables are removed:
#   - EmployeeNumber: unique row identifier; no predictive value.
#   - EmployeeCount, Over18, StandardHours: constant variables identified
#     in Section 3.6; zero variance means zero information gain.
# The original observations are preserved throughout the EDA, but three
# exploratory engineered variables (AgeGroup, IncomeGroup, AvgSatisfaction)
# are appended to df during the analysis. These derived columns are excluded
# again from df_ml before export, ensuring the ML dataset contains only the
# original 30 predictors plus the target variable.
#
# Engineered features created during EDA (AgeGroup, IncomeGroup,
# AvgSatisfaction) are excluded from df_ml. These will be re-created inside
# the tidymodels recipe using step_mutate() if required, ensuring that the
# Shiny prediction tab can still function from a 30-column user input tibble
# without needing pre-computed derived columns.

vars_to_remove_for_ml <- c("EmployeeNumber", "EmployeeCount",
                           "Over18", "StandardHours")
cat("\nVariables to remove for ML:\n")
print(vars_to_remove_for_ml)

df_ml <- df %>%
  select(-all_of(vars_to_remove_for_ml)) %>%
  select(-AgeGroup, -IncomeGroup, -AvgSatisfaction)

str(df_ml)
cat("\ndf_ml dimensions:", dim(df_ml), "\n")
cat("df_ml column names:\n")
cat(paste(sort(names(df_ml)), collapse = ", "), "\n")

write.csv(df_ml, "./DATA/df_ml.csv", row.names = FALSE)
cat("\ndf_ml.csv saved to ./DATA/\n")

# df_ml contains 31 columns: 30 predictors and the binary target Attrition.
# The column set is:
# Age, Attrition, BusinessTravel, DailyRate, Department,
# DistanceFromHome, Education, EducationField, EnvironmentSatisfaction,
# Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction,
# MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, OverTime,
# PercentSalaryHike, PerformanceRating, RelationshipSatisfaction,
# StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear,
# WorkLifeBalance, YearsAtCompany, YearsInCurrentRole,
# YearsSinceLastPromotion, YearsWithCurrManager.


# =====================================================
# 16. Key Business Takeaways
# =====================================================

# The following findings summarise the EDA and directly motivate the
# modelling decisions made in the ML script.
#
# 1. CLASS IMBALANCE: The target variable shows ~16.1% attrition: moderate
#    imbalance requiring SMOTE oversampling and J-index threshold optimisation
#    in the ML phase to avoid a trivially high accuracy from always predicting
#    "No".
#
# 2. STRONGEST CATEGORICAL PREDICTORS (by Cramér's V):
#    OverTime (V = 0.246), JobRole (V = 0.242), MaritalStatus (V = 0.177),
#    BusinessTravel (V = 0.128). Gender is not statistically significant
#    (p = 0.258).
#
# 3. STRONGEST NUMERIC PREDICTORS (by point-biserial |r|):
#    TotalWorkingYears (r = -0.171), JobLevel (r = -0.169),
#    YearsInCurrentRole (r = -0.161), MonthlyIncome (r = -0.160),
#    Age (r = -0.159), YearsWithCurrManager (r = -0.156),
#    StockOptionLevel (r = -0.137). All are negatively correlated:
#    higher values indicate lower attrition risk.
#
# 4. NOISE VARIABLES: DailyRate, HourlyRate, MonthlyRate show near-zero
#    correlation with MonthlyIncome (<0.04) and with Attrition (<0.06).
#    They are artefacts of the synthetic data generation process and are
#    expected to have negligible feature importance in the ML model.
#
# 5. OUTLIERS: Present in MonthlyIncome and tenure variables but legitimate
#    (senior staff, long-tenured employees). Not removed; tree-based models
#    are robust to outliers.
#
# 6. MULTICOLLINEARITY: MonthlyIncome ~ JobLevel (r = 0.95) is the strongest
#    pair; TotalWorkingYears ~ MonthlyIncome (r = 0.77) and several tenure
#    variables are also highly correlated. This is handled mainly by the 
#    tree-based algorithms used in the ML phase. Correlated predictors were 
#    retained and evaluated empirically by the models, while step_nzv() removed
#    uninformative low-variance features.
#
# 7. SATISFACTION: All four satisfaction variables show slightly lower scores
#    for leavers, but distributions overlap heavily. A composite score
#    captures overall engagement; individual variables capture distinct
#    dimensions. Both approaches will be tested in the recipe.
#
# 8. HIGH-RISK PROFILE: Young age (18–35, peak attrition ~35.8% for 18–25),
#    low monthly income (<$3,000, attrition ~28.6%), short company tenure
#    (< 5 years), overtime, frequent business travel, and single marital
#    status jointly characterise the highest-risk employees.
#
# 9. DATA QUALITY: Zero missing values, zero duplicates, three constant
#    variables removed. Dataset is synthetic (IBM), limiting the
#    generalisability of findings to real HR contexts.

# =====================================================
# End of EDA
# =====================================================

# =====================================================
# 17. Save All Outputs
# =====================================================

# All plots and tables are saved to a dedicated output folder.
# The folder is created automatically if it does not yet exist.

output_dir <- "./OUTPUT/EDA"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# ----- 17.1 Save tables as CSV -----

write.csv(chi_sq_results,            file.path(output_dir, "chi_sq_results.csv"),            row.names = FALSE)
write.csv(pb_correlations,           file.path(output_dir, "pb_correlations.csv"),           row.names = FALSE)
write.csv(noise_check,               file.path(output_dir, "noise_check.csv"),               row.names = FALSE)
write.csv(outlier_summary,           file.path(output_dir, "outlier_summary.csv"),           row.names = FALSE)
write.csv(attrition_numeric_summary, file.path(output_dir, "attrition_numeric_summary.csv"), row.names = FALSE)
write.csv(cor_pairs,                 file.path(output_dir, "cor_pairs_strong.csv"),          row.names = FALSE)

cat("Tables saved to:", output_dir, "\n")

# ----- 17.2 Save plots as PNG -----

# Target distribution
p_target <- ggplot(df, aes(x = Attrition, fill = Attrition)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.1))) +
  scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(title = "Employee Attrition Distribution",
       x = "Attrition", y = "Number of Employees") +
  theme_minimal() + theme(legend.position = "none")
ggsave(file.path(output_dir, "01_attrition_distribution.png"), p_target, width = 6, height = 4, dpi = 150)

# Point-biserial correlations
p_pb <- ggplot(pb_correlations, aes(x = reorder(Variable, r_pb), y = r_pb)) +
  geom_col(aes(fill = r_pb > 0), show.legend = FALSE) +
  scale_fill_manual(values = c("TRUE" = "#E74C3C", "FALSE" = "#3498DB")) +
  coord_flip() +
  labs(title = "Point-Biserial Correlation with Attrition",
       x = NULL, y = "Correlation (r)") +
  theme_minimal()
ggsave(file.path(output_dir, "02_pb_correlations.png"), p_pb, width = 7, height = 6, dpi = 150)

# Attrition rate plots
for (var in c("OverTime", "JobRole", "Department", "MaritalStatus",
              "BusinessTravel", "EducationField", "Gender",
              "AgeGroup", "IncomeGroup")) {
  p <- df %>%
    group_by(.data[[var]]) %>%
    summarise(attrition_rate = mean(Attrition == "Yes"), .groups = "drop") %>%
    ggplot(aes(x = reorder(.data[[var]], attrition_rate), y = attrition_rate)) +
    geom_col(fill = "steelblue") +
    geom_text(aes(label = paste0(round(attrition_rate * 100, 1), "%")),
              hjust = -0.1, size = 3) +
    scale_y_continuous(labels = percent, expand = expansion(mult = c(0, 0.15))) +
    coord_flip() +
    labs(title = paste("Attrition Rate by", var), x = NULL, y = "Attrition Rate") +
    theme_minimal()
  ggsave(file.path(output_dir, paste0("03_attrition_rate_", var, ".png")),
         p, width = 7, height = 4, dpi = 150)
}

# Composite satisfaction violin plot
p_sat <- ggplot(df, aes(x = Attrition, y = AvgSatisfaction, fill = Attrition)) +
  geom_violin(alpha = 0.6, trim = FALSE) +
  geom_boxplot(width = 0.15, fill = "white") +
  scale_fill_manual(values = c("Yes" = "#E74C3C", "No" = "#3498DB")) +
  labs(title = "Average Satisfaction Score by Attrition",
       y = "Average Satisfaction (1-4)") +
  theme_minimal() + theme(legend.position = "none")
ggsave(file.path(output_dir, "04_avg_satisfaction_violin.png"), p_sat, width = 6, height = 4, dpi = 150)

# Correlation matrix
png(file.path(output_dir, "05_correlation_matrix.png"), width = 1200, height = 1000, res = 120)
corrplot(cor_matrix, method = "color", type = "upper", tl.cex = 0.6,
         addCoef.col = "black", number.cex = 0.5)
dev.off()

cat("All plots saved to:", output_dir, "\n")
cat("Done.\n")